// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartMoney.Infrastructure.Persistence;

#nullable disable

namespace SmartMoney.Infrastructure.Migrations
{
    [DbContext(typeof(SmartMoneyDbContext))]
    [Migration("20260809122619_AddMarketClose")]
    partial class AddMarketClose
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartMoney.Domain.Entities.JobRunLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("JobName", "Date");

                    b.ToTable("job_run_log", (string)null);
                });

            modelBuilder.Entity("SmartMoney.Domain.Entities.MarketBias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<double>("FinalScore")
                        .HasColumnType("float");

                    b.Property<double>("RawBias")
                        .HasColumnType("float");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<double>("ShockScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("market_bias", (string)null);
                });

            modelBuilder.Entity("SmartMoney.Domain.Entities.MarketClose", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double>("Close")
                        .HasColumnType("float");

                    b.HasKey("Date", "Symbol");

                    b.ToTable("market_close", (string)null);
                });

            modelBuilder.Entity("SmartMoney.Domain.Entities.ParticipantMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CallZLong")
                        .HasColumnType("float");

                    b.Property<double>("CallZShort")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<double>("FuturesZLong")
                        .HasColumnType("float");

                    b.Property<double>("FuturesZShort")
                        .HasColumnType("float");

                    b.Property<string>("Participant")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<double>("ParticipantBias")
                        .HasColumnType("float");

                    b.Property<double>("PutZLong")
                        .HasColumnType("float");

                    b.Property<double>("PutZShort")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Participant")
                        .IsUnique();

                    b.ToTable("participant_metrics", (string)null);
                });

            modelBuilder.Entity("SmartMoney.Domain.Entities.ParticipantRawData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CallOiChange")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<double>("FuturesChange")
                        .HasColumnType("float");

                    b.Property<double>("FuturesNet")
                        .HasColumnType("float");

                    b.Property<string>("Participant")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<double>("PutOiChange")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Participant")
                        .IsUnique();

                    b.ToTable("participant_raw_data", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
